Fix Python module being broken
frequenz-floss/frequenz-api-dispatch pull request #10
Opened 2023-06-16 12:34 UTC by christianparpart

It seems like the fcr sub directory was recently added (0.7.0) and that its respective `py` directory structure was not updated respectively. I added an `__init__.py`, and a `py.typed` to it, analogous to its parent directory. That SEEMS to fix the import issue I had on 0.8.1 (simply latest, tried nothing else above 0.6.0). I am not sure though if `py.typed` addition is needed.

2023-06-16 13:04 UTC, Marenz commented on py/frequenz/api/dispatch/fcr/__init__.py
> +Copyright © 2022 Frequenz Energy-as-a-Service GmbH.
2023 :P

2023-06-16 14:20 UTC, llucax requested changes, later dismissed

2023-06-16 14:20 UTC, llucax commented on py/frequenz/api/dispatch/fcr/py.typed
This file is not needed, you should remove it.

2023-06-16 14:20 UTC, llucax commented on py/frequenz/api/dispatch/fcr/__init__.py
> +"""
The license and copyright info should be in a comment. Also the doc should be a bit more accurate :)

```suggestion
# License: MIT
# Copyright © 2023 Frequenz Energy-as-a-Service GmbH

"""FCR related dispatched."""
```

2023-06-16 14:20 UTC, llucax commented
Please also add a test. This didn't break the CI because nothing is imported from `frequenz.api.dispatch.fcr` in the tests.

2023-06-16 17:36 UTC, christianparpart commented
Actually, on REPL it broke with existing tests.

2023-06-19 15:11 UTC, christianparpart commented
> Please also add a test. This didn't break the CI because nothing is imported from frequenz.api.dispatch.fcr in the tests.


added

2023-06-19 15:22 UTC, stefan-brus-frequenz approved these changes

2023-06-19 15:22 UTC, merged