Add `update_time` field to Dispatch message
frequenz-floss/frequenz-api-dispatch pull request #23
Opened 2023-07-24 12:45 UTC by stefan-brus-frequenz

2023-07-24 15:08 UTC, tiyash-basu-frequenz submitted a review, later dismissed

2023-07-24 15:42 UTC, thomas-nicolai-frequenz commented on proto/frequenz/api/dispatch/dispatch.proto
> +  google.protobuf.Timestamp update_time = 11;
I suggest to insert them as 4 and 5 instead.

2023-07-24 15:45 UTC, thomas-nicolai-frequenz commented on proto/frequenz/api/dispatch/dispatch.proto
>    DispatchComponentSelector selector = 6;
uh `optional string type = 3;` should be removed. Changing that would create quite some issues.

2023-07-24 15:46 UTC, thomas-nicolai-frequenz commented on proto/frequenz/api/dispatch/dispatch.proto
>    DispatchComponentSelector selector = 6;
Also keep in mind that start_time has to be in the future! Can you please also add that to the documentation? Only start_time with a future date should be allowed to be updated.

2023-07-25 11:49 UTC, thomas-nicolai-frequenz commented on proto/frequenz/api/dispatch/dispatch.proto
> +  // The starting timestamp has to be in the future when creating a dispatch
I'm not 100% certain we should be defining it like that. What if someone wants to dispatch something NOW?

2023-07-25 11:49 UTC, thomas-nicolai-frequenz commented on proto/frequenz/api/dispatch/dispatch.proto
> +  // The starting timestamp has to be in the future when updating a dispatch
Same here. We might want to support NOW as the smallest possible value.

2023-07-25 11:50 UTC, thomas-nicolai-frequenz requested changes
The NOW topic should be solved in case someone wants to dispatch something immediately in an emergency situation.

2023-07-25 14:44 UTC, thomas-nicolai-frequenz approved these changes

2023-07-25 14:53 UTC, tiyash-basu-frequenz approved these changes

2023-07-25 14:53 UTC, merged